apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-test
        image: 117612009356.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:latest
      nodeSelector:
        eks.amazonaws.com/nodegroup: nodegroup-web
