apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-hname
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: echo-hname
        image: 739362892804.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:latest
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: nodegroup-web
